### ISSUE TITLE
Console needs text limit & send command to all bots

### ISSUE THREAD

**Issue by Hexatronic01** [qtTF2/catwire#7]
If the log file directly goes to the console it should have a text limit so you do not need to scroll down all the way to the bottom of the page to get to the console, Another feature I think should be added is an option to send commands to all bots.

**Comment by AXDWT** [comment]
i agree with that
console textbox needs text limit. the limit is how much tf2 limits their console text

**Comment by qtTF2** [comment]
i have added send cmd to all bots feature if u did update its in the IPC settings, im considering adding a limit on how much far the console should read from game logs
